Bluescape/helm

charts/bluescape-monitoring-dashboards/Chart.yaml

Signed-off-by: Jim Conner <snafu.x@gmail.com>

bumped version in Chart.yaml

---

charts/bluescape-monitoring-dashboards/Chart.yaml
charts/bluescape-monitoring-dashboards/templates/99_analytics_computeresources_pods_dashboard/configmap.yaml
charts/bluescape-monitoring-dashboards/templates/99_analytics_computeresources_pods_dashboard/dashboard.yaml

SRE-1456: Adding Analytics Dashboard

Adding Analytics Dashboard

---

charts/bluescape-monitoring-dashboards/templates/60_unified_servicestatus_dashboard/configmap.yaml
charts/bluescape-monitoring-dashboards/templates/60_unified_servicestatus_dashboard/dashboard.yaml

Please review and merge this PR:
https://grafana.a-uat.dev.bluescape.io/d/m9yGD09Wk/service-status?orgId=1

Adding new service status dashboard for bluescape - [SRE-1616]

---

charts/bluescape-monitoring-dashboards/templates/32_lambda_metrics_dashboard/configmap.yaml
charts/bluescape-monitoring-dashboards/templates/32_lambda_metrics_dashboard/dashboard.yaml

Please review and merge the PR.

Grafana dashboard for lambda function - [SRE-1641]

---

charts/bluescape-monitoring-dashboards/templates/60_unified_servicestatus_dashboard/configmap.yaml

Please review and merge this PR:
https://grafana.a-us.prod.bluescape.io/d/d06278d15608be63a8b14764db1514fac03ebf96/service-status?orgId=1&refresh=5s

Improvising Service Status Dashboard - [SRE-1684]

---

charts/bluescape-monitoring-grafana/templates/grafana.yaml
charts/bluescape-monitoring-grafana/templates/sentry-plugin-creds.yaml
charts/bluescape-monitoring-grafana/values.yaml

Related PR:
https://github.com/Bluescape/terraform-helm-k8s-generic/pull/183

SRE-1686 adding grafana-sentry-datasource plugin

---

charts/n8n/.helmignore
charts/n8n/Chart.yaml
charts/n8n/templates/NOTES.txt
charts/n8n/templates/_helpers.tpl
charts/n8n/templates/deployment-main.yaml
charts/n8n/templates/deployment-webhook.yaml
charts/n8n/templates/deployment-worker.yaml
charts/n8n/templates/hpa-worker.yaml
charts/n8n/templates/ingress.yaml
charts/n8n/templates/required.yaml
charts/n8n/templates/service-main.yaml
charts/n8n/templates/service-webhook.yaml
charts/n8n/templates/serviceaccount.yaml
charts/n8n/values.yaml

This deploys n8n in a queue mode by default with 1 main node, 2 workers, and 2 webhook handlers

NEX-2099 - Adding 0.1.0 first version of the helm chart for n8n

---

charts/bluescape-eks-aux/CHANGELOG.md
charts/bluescape-eks-aux/Chart.yaml
charts/bluescape-eks-aux/templates/external-secret-argocd.yaml
charts/bluescape-eks-aux/templates/external-secret-github.yaml
charts/bluescape-eks-aux/values.yaml

reverting this change: https://github.com/Bluescape/helm/pull/29/files#diff-6e7108c560b6fe94f5b8f247c5fd8b6d4f2269f2d3191a0205ae6af08d90aeb0

NEX-2092 - reverting argocd external-secrets change

---

charts/bluescape-monitoring-dashboards/Chart.yaml
charts/bluescape-monitoring-dashboards/templates/15b_qa-front-end-summary/configmap.yaml

Fixed parsing error in the config map since there was an additional space from formatting and updated the graphs to add cpu usage.

QAA-6718: Update QA Frontend Summary metrics

---

.github/workflows/lint.yml

Added a linting check so that we don't merge changes which can't be parsed by helm.

NEX-2316: Add linting workflow for helm charts

---

charts/bluescape-monitoring-dashboards/Chart.yaml
charts/bluescape-monitoring-dashboards/templates/7a_logging-operator/configmap.yaml

NEX-2324 - Showing output buffers in logging-operator dashboard / improvements to Loki dashboard

---

charts/bluescape-monitoring-grafana/templates/external-secret-sentry-plugin.yaml

Making a small update to the variable names
Related:
https://github.com/Bluescape/infrastructure/pull/5125/files

SRE-1686-1 update variable name for sentry plugin creds

---

charts/cert-manager-sync/.helmignore
charts/cert-manager-sync/Chart.yaml
charts/cert-manager-sync/templates/NOTES.txt
charts/cert-manager-sync/templates/_helpers.tpl
charts/cert-manager-sync/templates/deployment.yaml
charts/cert-manager-sync/templates/hpa.yaml
charts/cert-manager-sync/templates/serviceaccount.yaml
charts/cert-manager-sync/values.yaml

tested in SRE cluster successfully
Signed-off-by: Jim Conner <snafu.x@gmail.com>

SRE-2098: cert-manager-sync chart addition

---

charts/bluescape-monitoring-dashboards/Chart.yaml
charts/bluescape-monitoring-dashboards/templates/15b_qa-front-end-summary/configmap.yaml

Tiny change to make the panel compatible with the performanceHelper

QAA-7222: Change fps measurement to frames.fps for performanceHelper support

---

charts/cert-manager-sync/Chart.yaml
charts/cert-manager-sync/templates/cluster-role.yaml
charts/cert-manager-sync/values.yaml

Signed-off-by: Jim Conner <snafu.x@gmail.com>
Note that a template run and a manual run of this chart succeeds on sre1.
```
at 14:22:30 ❯ helm upgrade --install -n cert-manager cert-manager-sync cert-manager-sync -f current-helm-values.yaml                                                                                                                                                                                        
Release "cert-manager-sync" has been upgraded. Happy Helming!                                                                                                                                                                                                                                               
NAME: cert-manager-sync …
```

SRE-2129: fixed chart for missing clusterrole in template

---

charts/bluescape-monitoring-dashboards/Chart.yaml
charts/bluescape-monitoring-dashboards/templates/33_apollo_graphql_metrics/configmap.yaml
charts/bluescape-monitoring-dashboards/templates/33_apollo_graphql_metrics/dashboard.yaml

Please review and merge this PR, Tested in uat.
https://grafana.b-uat.dev.bluescape.io/d/RQRYVAmnz/apollo-graphql-metrics?orgId=1&refresh=10s&from=now-24h&to=now&var-Datasource=Prometheus

Added new graphql dashboard for isam

---

charts/bluescape-monitoring-dashboards/Chart.yaml
charts/bluescape-monitoring-dashboards/templates/96_mongodb/configmap.yaml
charts/bluescape-monitoring-dashboards/templates/96_mongodb/dashboard.yaml

Please review and merge this PR:
Changes already applied in sre1 cluster.
https://grafana.b-sre1.dev.bluescape.io/d/AyWQt9jWk/mongodb?orgId=1&refresh=5s

SRE-2183 - Added updated mongo db dashboard.

---

charts/bluescape-monitoring-dashboards/Chart.yaml
charts/bluescape-monitoring-dashboards/templates/100_performance-image-upload/configmap.yaml
charts/bluescape-monitoring-dashboards/templates/100_performance-image-upload/dashboard.yaml

https://jira.common.bluescape.com/browse/COL-5221
- added a new dashboard for image upload performance metrics
- tested on stg2 cluster

COL-5221 Revise the worker service dashboard to use the new metrics

---

charts/bluescape-monitoring-dashboards/Chart.yaml
charts/bluescape-monitoring-dashboards/templates/101_performance-elementary/configmap.yaml
charts/bluescape-monitoring-dashboards/templates/101_performance-elementary/dashboard.yaml

https://jira.common.bluescape.com/browse/COL-5236
- added a new dashboard to monitor elementary performance
Tested the new dashboard on stg2 environment

COL-5236 Create a new performance dashboard for elementary service

---

charts/bluescape-monitoring-dashboards/Chart.yaml
charts/bluescape-monitoring-dashboards/templates/15b_qa-front-end-summary/configmap.yaml

- Set default measurement to `mean`
- Made all panels full width so that you can see the `range` metric

QAA-7229: Update front end summary dashboard

---

charts/saaras/Chart.yaml
charts/saaras/README.md
charts/saaras/crds/enroute.saaras.io_gatewayhosts.yaml
charts/saaras/crds/enroute.saaras.io_globalconfigs.yaml
charts/saaras/crds/enroute.saaras.io_httpfilters.yaml
charts/saaras/crds/enroute.saaras.io_policyoverlays.yaml
charts/saaras/crds/enroute.saaras.io_routefilters.yaml
charts/saaras/crds/enroute.saaras.io_serviceroutes.yaml
charts/saaras/crds/enroute.saaras.io_tlscertificatedelegations.yaml
charts/saaras/crds/gateway.networking.k8s.io_gatewayclasses.yaml
charts/saaras/crds/gateway.networking.k8s.io_gateways.yaml
charts/saaras/crds/gateway.networking.k8s.io_httproutes.yaml
charts/saaras/crds/gateway.networking.k8s.io_referencegrants.yaml
charts/saaras/templates/NOTES.txt
charts/saaras/templates/_helpers.tpl
charts/saaras/templates/deployment.yaml
charts/saaras/templates/hpa.yaml
charts/saaras/templates/istio-strict-mtls.yaml
charts/saaras/templates/rolebinding.yaml
charts/saaras/templates/roles.yaml
charts/saaras/templates/service.yaml
charts/saaras/templates/serviceaccount.yaml
charts/saaras/values.yaml

NEX-2713: Enroute Production Image and Helm chart

---

charts/saaras/Chart.yaml
charts/saaras/templates/rolebinding.yaml
charts/saaras/templates/serviceaccount.yaml

NEX-2719: Infrastructure Deploy Enroute to STG2 cluster

---

charts/saaras/Chart.yaml
charts/saaras/crds/enroute.saaras.io_gatewayhosts.yaml
charts/saaras/crds/enroute.saaras.io_globalconfigs.yaml
charts/saaras/crds/enroute.saaras.io_httpfilters.yaml
charts/saaras/crds/enroute.saaras.io_policyoverlays.yaml
charts/saaras/crds/enroute.saaras.io_routefilters.yaml
charts/saaras/crds/enroute.saaras.io_serviceroutes.yaml
charts/saaras/crds/enroute.saaras.io_tlscertificatedelegations.yaml
charts/saaras/crds/gateway.networking.k8s.io_udproutes.yaml
charts/saaras/templates/roles.yaml

update the EnRoute chart to the version 0.8.4

NEX-2798: Infrastructure Add TCP Mappings to EnRoute (WebRTC)

---

charts/bluescape-monitoring-dashboards/Chart.yaml
charts/bluescape-monitoring-dashboards/templates/11_qa-k6/configmap.yaml

QAA-1431: Improve k6 dashboard variables

---

charts/saaras/Chart.yaml
charts/saaras/templates/deployment.yaml

adding a security context to the init container

NEX-2902: Configure a Security Context for Enroute

---

charts/saaras/Chart.yaml
charts/saaras/templates/deployment.yaml
charts/saaras/templates/service-admin.yaml

Adding an admin service for metrics

NEX-2921: EnRout metrics are missed in Grafana

---

charts/saaras/Chart.yaml

aligning the version with the origin helm chart

NEX-2962: Update EnRoute

---

charts/saaras/Chart.yaml
charts/saaras/templates/NOTES.txt

getting rid of the license term

NEX-3016: Infrastructure Get rid of the licence term

---

charts/bluescape-monitoring-dashboards/Chart.yaml
charts/bluescape-monitoring-dashboards/templates/61_k8s-cluster-dashboard/configmap.yaml

Please see ticket for details.
Dashboard is currently deployed in GSTG1 for viewing.

Fed 941 - thomas/fix kube related metrics

---

charts/bluescape-monitoring-dashboards/Chart.yaml
charts/bluescape-monitoring-dashboards/templates/1_argocd/configmap.yaml

There appears to be a duplicate kind entry in configmap file, removing it & also verified all good in rest all folders

Fixing duplicate configmap entry (argocd) SRE-2825

---

charts/bluescape-monitoring-dashboards/Chart.yaml
charts/bluescape-monitoring-dashboards/templates/33_apollo_graphql_metrics/configmap.yaml

See FED-928 for details
The Apollo GraphQL metrics dashboard had some broken panels.  This PR fixes those.

fed-928/fix missing GraphQL panels

---

charts/bluescape-banzai-dashboards/Chart.yaml
charts/bluescape-banzai-dashboards/templates/_helpers.tpl
charts/bluescape-monitoring-dashboards/Chart.yaml
charts/bluescape-monitoring-dashboards/templates/_helpers.tpl

**Relevant Infra PR:**
https://github.com/Bluescape/infrastructure/pull/7216

SRE-2998 - Adding common label for grabbing grafana dashboards

---

charts/cert-manager-sync/Chart.yaml
charts/cert-manager-sync/templates/_helpers.tpl
charts/cert-manager-sync/values.yaml

Update the chart for the latest version of cert-manager-sync
successful testing: https://app.env0.com/p/a5a1901a-87cb-4067-9bfc-9af7dc835334/environments/1e352270-8723-4027-bb8a-1b06cfd2aef1?tabname=deployment-logs

latest and greatest

---

charts/mongodb/Chart.yaml
charts/mongodb/templates/secrets.yaml

fixing backward compatibility error

NEX-3322: Infrastructure Investigate upgrading in-cluster mongo 4.4 to 5.0

---

charts/saaras/Chart.yaml
charts/saaras/templates/service-admin.yaml

adding envoy-admin port to the admin service

NEX-3358: Infrastructure Update EnRoute to version 1.0.14

---

charts/bluescape-monitoring-dashboards/Chart.yaml
charts/bluescape-monitoring-dashboards/templates/40_victoriametrics-cluster/configmap.yaml

For this PR I have:
1- Updated the **Victoria Metrics - Cluster** dashboard as it was showing an annotations error when the Prometheus datasource was selected.
2- Updated the minimum interval of some of the **Victoria Metrics - Cluster** dashboard's panels which were not rendering correctly.

sre-2725: fix VM dashboard's annotations

---

charts/credrotation-operator/crds/dbrc-operator.yaml
charts/credrotation-operator/values.yaml

tested in infra1 successfully. This is a new project.

FED-1451: update to new crd and added comment to values file

---

charts/credrotation-operator/Chart.yaml

CredRotationOperator Version Fix
