Bluescape/helm

charts/bluescape-monitoring-dashboards/templates/61_k8s-cluster-dashboard/configmap.yaml, charts/bluescape-monitoring-dashboards/templates/61_k8s-cluster-dashboard/dashboard.yaml
Please review and merge this PR.
Already tested the dashboard in grafana.
https://grafana.a-us.prod.bluescape.io/d/taQlRuxik/k8s-cluster-metrics?orgId=1&refresh=1m
=> Added new dashboard for k8s cluster metrics - [SRE-1446]

charts/bluescape-monitoring-dashboards/Chart.yaml, charts/bluescape-monitoring-dashboards/templates/83_document_upload_metrics/configmap.yaml, charts/bluescape-monitoring-dashboards/templates/90_all-nodes/configmap.yaml, charts/bluescape-monitoring-dashboards/templates/94_synthetic_tests/dashboard.yaml
Fix missing dashboards
- Self-Serve Dashboard
- Analytics Dashbaord
There were some typos in other dashboards and this is the fix to make sure all the missing dashboards are deployed successfully.
=> Sre 1476/fix missing dashboards

charts/bluescape-eks-aux/CHANGELOG.md, charts/bluescape-eks-aux/Chart.yaml, charts/bluescape-eks-aux/templates/cluster-issuer-letsencrypt-extra.yaml, charts/bluescape-eks-aux/templates/cluster-issuer-letsencrypt-prod-dns.yaml, charts/bluescape-eks-aux/templates/cluster-issuer-letsencrypt-prod.yaml
Adding capability to use old and new api version for cert-manager issuer
Tested manually on a-neb cluster successfully
Notes:
This is to support the new cert-manager version 1.8.2
=> NEX-2046 - Adding capability to use old and new api version for cert-manager issuer

charts/bluescape-emissary-crds/Chart.yaml, charts/bluescape-emissary-crds/crds/aes-crds.yaml, charts/bluescape-emissary-crds/crds/aes-creds-3_1.yaml, charts/bluescape-emissary-crds/values.yaml
For now, it will default to version 2 CRDs.
Use the "version" field to switch between 2.x and 3.x (see comment in values.yaml)
=> NEX-2139 - Updates to support AES 3.1 CRDs

charts/bluescape-eks-aux/CHANGELOG.md, charts/bluescape-eks-aux/Chart.yaml, charts/bluescape-eks-aux/templates/cluster-issuer-letsencrypt-extra.yaml
- changing Extra ClusterIssuer to use Secret references for `accessKeyID`
Tested manually on `a-infra1`
=> NEX-1282 - updating bluescape-eks-aux to v0.11.0

charts/istio-additions/Chart.yaml, charts/istio-additions/templates/prometheus-metrics-proxy-service.yaml
This is a bugfix for the previous RP https://github.com/Bluescape/helm/pull/25
This PR fixes a bug of the absence of necessary labels in the Kubernetes resources to add
TESTED=the new version has been tested on the STG environment using the https://github.com/Bluescape/helm/releases/tag/istio-additions-0.2.2-alpha package
=> Nex-2166 - Resource metrics missing in LENS for andromeda/doe cluster

charts/bluescape-monitoring-dashboards/Chart.yaml, charts/bluescape-monitoring-dashboards/templates/15b_qa-front-end-summary/configmap.yaml, charts/bluescape-monitoring-dashboards/templates/15b_qa-front-end-summary/dashboard.yaml
Adding the small start to a new QA dashboard to present summarized frontend performance metrics while running automation. This is essentially to deprecate the current front-end metrics dashboard as it's highly inefficient on queries and difficult to read. (yes, that's my fault from 3 years ago).
=> QAA-6718: Create QA FrontEnd Summary dashboard

.github/scripts/verify_chart_version_update.sh, .github/workflows/preflight.yml
Check added in preflight to verify that the version of the chart has been updated whenever the chart yaml has been. 
Run when the chart version wasn't modified: https://github.com/Bluescape/helm/actions/runs/3282901673/jobs/5406925600
Fails as expected
Run where the chart version was modified: https://github.com/Bluescape/helm/actions/runs/3282916555/jobs/5406961212
Passes as expected
=> NEX-2318: Add preflight check for chart version updates

charts/bluescape-eks-aux/Chart.yaml, charts/bluescape-eks-aux/templates/external-secret-aes-edge-stack.yaml, charts/bluescape-eks-aux/templates/external-secret-argocd.yaml, charts/bluescape-eks-aux/templates/external-secret-extra-cluster-issuer.yaml, charts/bluescape-eks-aux/templates/external-secret-github.yaml, charts/bluescape-eks-aux/templates/external-secret-gpm.yaml, charts/bluescape-eks-aux/templates/external-secret-loki-basic-auth.yaml, charts/bluescape-eks-aux/templates/external-secret-loki-ingress-auth.yaml, charts/bluescape-eks-aux/templates/external-secret-prometheus-metrics.yaml, charts/bluescape-eks-aux/templates/external-secret-threatstack.yaml, charts/bluescape-eks-aux/templates/vault-backend-cs.yaml, charts/bluescape-eks-aux/templates/vault-cr.yaml, charts/bluescape-eks-aux/values.yaml
**Target Chart Version : 0.15.0**
- New Vault (HA, raft storage) - provisioned from EKS project. 
```
vault_cr:
enabled: false
image: vault
imageTag: "1.6.0"
bound_service_account_names: []
bound_service_account_namespaces: []
storageClass: "persistent"
clusterSize: 3
serviceAccount: "vault"
priorityClassName: "system-node-critical"
tls_disable: false
istio_enable: false
local_vault_addr: "https://vault.vault.svc.cluster.local:8200"
setup_vault_as_cluster_secret_store: false
```
- Adding support for NEW external-secrets-operator and vault-backed via `ClusterSecretStore`
- New manifests for secrets synced via `external-secrets-operator`
=> NEX-2227 - Adding support for new BanzaiCloud Vault

charts/bluescape-monitoring-dashboards/Chart.yaml, charts/bluescape-monitoring-dashboards/templates/15_qa-front-end/configmap.yaml, charts/bluescape-monitoring-dashboards/templates/15b_qa-front-end-summary/configmap.yaml
- Switched the QA summary dashboard to use the new `ph_summary` 
- Simplified each panel to a single query for all fields using `$col` as the alias
- Simplified the Front End dashboard to have significantly less data queried on load
- Populated the db on alpha with some test results, applied dashboard
Results below.
=> QAA-6718: Switch QA dashboard to new datasource

charts/bluescape-monitoring-dashboards/Chart.yaml, charts/bluescape-monitoring-dashboards/templates/7a_logging-operator/configmap.yaml
Improvements to buffer disk usage charts to make it more clear how buffers are bing used.
=> NO-JIRA - Logging-operator dashboard improvements

charts/istio-additions/Chart.yaml, charts/istio-additions/templates/edge-stack-tls-context.yaml, charts/istio-additions/templates/edge-stack-tracing-service.yaml, charts/istio-additions/values.yaml
This change is exclusively required for packaging harness. For all other K8s clusters, this configuration is generated dynamically in TF and applied at runtime.
=> CD-625: Istio-additions Chart Update (for packaging harness)

charts/bluescape-monitoring-dashboards/Chart.yaml, charts/bluescape-monitoring-dashboards/templates/84_backend_rendering_api_dashboard/configmap.yaml, charts/bluescape-monitoring-dashboards/templates/84_backend_rendering_api_dashboard/dashboard.yaml
Please review and merge the PR for backend rendering api dashboard.
Tested in STG1 environment:
https://grafana.b-stg1.preprod.bluescape.io/d/4AUVuBK4z/backend-rendering-api?orgId=1&from=now-2d&to=now&var-datasource=loki-stg1&var-instance=&var-namespace=stg1
=> SRE-1914 - Adding new grafana dashboard for backend rendering api

charts/bluescape-monitoring-dashboards/Chart.yaml, charts/bluescape-monitoring-dashboards/templates/84_backend_rendering_api_dashboard/dashboard.yaml
I believe this was causing issues during the latest base apps run after updating the grafana operator version. 
```
Error: error validating "": error validating data: [ValidationError(GrafanaDashboard.spec): unknown field "name" in org.integreatly.v1alpha1.GrafanaDashboard.spec, ValidationError(GrafanaDashboard.spec): missing required field "json" in org.integreatly.v1alpha1.GrafanaDashboard.spec]
with module.k8s.helm_release.grafana-dashboards[0]
on ../../../../../../modules/helm/k8s-generic/grafana-operator.tf line 272, in resource "helm_release" "grafana-dashboards":
```
Basing this off of KG's changes: https://github.com/Bluescape/helm/commit/0f84c71c62327670b8393f471b488b6df4cdc0f7
=> Fix JSON not being assigned to "" in backend-rendering-api-dashboard

charts/bluescape-monitoring-dashboards/Chart.yaml, charts/bluescape-monitoring-dashboards/templates/15b_qa-front-end-summary/configmap.yaml
Adding a new test duration panel to the front end summary dashboard
=> QAA-7227: Add test duration to the frontend summary dashboard

charts/bluescape-monitoring-grafana/Chart.yaml, charts/bluescape-monitoring-grafana/templates/grafana-env-secret.yaml, charts/bluescape-monitoring-grafana/templates/grafana.yaml, charts/bluescape-monitoring-grafana/values.yaml
- Adds ability to send through a list of environment vars to add to the grafana process (disabled by default)
=> NEX-2492 - Ability to pass additional environment vars to Grafana instance for custom config

charts/bluescape-monitoring-dashboards/Chart.yaml, charts/bluescape-monitoring-dashboards/templates/15b_qa-front-end-summary/configmap.yaml
- Added new frametime panel
- Added Calculation variable to the dashboard that is used for the fields of all panels
=> QAA-7696: Add frametimes to the front end summary dashboard

charts/bluescape-monitoring-dashboards/Chart.yaml, charts/bluescape-monitoring-dashboards/templates/15b_qa-front-end-summary/configmap.yaml
- Removed gradients
- Transparent backgrounds
- Added thresholds to the FPS and frame time panels
=> QAA-8529: Add thresholds to the FPS and frametime panels

charts/bluescape-monitoring-dashboards/Chart.yaml, charts/bluescape-monitoring-dashboards/templates/4_express-app/configmap.yaml
Made some small changes in the Application Express App dashboard by adjusting the names of some metrics and changing the data source to Prometheus. 
Metrics 'http_request_duration_seconds_count' and 'http_request_duration_seconds_sum' needed to be changed to 'prometheus_http_request_duration_seconds_count' and 'prometheus_http_request_duration_seconds_sum' in all four panels as well as in the variables job and namespace.
=> Fed-927 Fixed Application Express App dashboard

charts/raw/Chart.yaml, charts/raw/README.md, charts/raw/templates/_helpers.tpl, charts/raw/templates/resources.yaml, charts/raw/values.yaml
Importing from https://artifacthub.io/packages/helm/itscontained/raw  
- The `raw` chart takes a list of Kubernetes resources and merges each resource with a default metadata.labels map and installs the result.
- The Kubernetes resources can be "raw" ones defined under the resources key, or "templated" ones defined under the templates key.
**TODO**
- Version to be bumped.
=> NEX-3045 - Importing `raw` chart

charts/istio-additions/Chart.yaml, charts/istio-additions/values.yaml
Version upgrade required for kiali/kiali-operator & jaeger/jaeger-operator to protect against bad source telemetry.
**Related to**
- https://github.com/Bluescape/infrastructure/pull/6914
=> New Chart version for istio-additions (0.2.6)

charts/credrotation-operator/crds/dbrc-operator.yaml
the status object, for best practices, should have all of the status objects used by the CR.
=> FED-1458: update to status object of the crd
